/*
Copyright Saurov.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/souravbiswassanto/crd/pkg/apis/makecrd.com/v1alpha1"
	makecrdcomv1alpha1 "github.com/souravbiswassanto/crd/pkg/client/applyconfiguration/makecrd.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCrds implements CrdInterface
type FakeCrds struct {
	Fake *FakeMakecrdV1alpha1
	ns   string
}

var crdsResource = v1alpha1.SchemeGroupVersion.WithResource("crds")

var crdsKind = v1alpha1.SchemeGroupVersion.WithKind("Crd")

// Get takes name of the crd, and returns the corresponding crd object, and an error if there is any.
func (c *FakeCrds) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Crd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(crdsResource, c.ns, name), &v1alpha1.Crd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crd), err
}

// List takes label and field selectors, and returns the list of Crds that match those selectors.
func (c *FakeCrds) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CrdList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(crdsResource, crdsKind, c.ns, opts), &v1alpha1.CrdList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CrdList{ListMeta: obj.(*v1alpha1.CrdList).ListMeta}
	for _, item := range obj.(*v1alpha1.CrdList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested crds.
func (c *FakeCrds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(crdsResource, c.ns, opts))

}

// Create takes the representation of a crd and creates it.  Returns the server's representation of the crd, and an error, if there is any.
func (c *FakeCrds) Create(ctx context.Context, crd *v1alpha1.Crd, opts v1.CreateOptions) (result *v1alpha1.Crd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(crdsResource, c.ns, crd), &v1alpha1.Crd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crd), err
}

// Update takes the representation of a crd and updates it. Returns the server's representation of the crd, and an error, if there is any.
func (c *FakeCrds) Update(ctx context.Context, crd *v1alpha1.Crd, opts v1.UpdateOptions) (result *v1alpha1.Crd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(crdsResource, c.ns, crd), &v1alpha1.Crd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crd), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCrds) UpdateStatus(ctx context.Context, crd *v1alpha1.Crd, opts v1.UpdateOptions) (*v1alpha1.Crd, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(crdsResource, "status", c.ns, crd), &v1alpha1.Crd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crd), err
}

// Delete takes name of the crd and deletes it. Returns an error if one occurs.
func (c *FakeCrds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(crdsResource, c.ns, name, opts), &v1alpha1.Crd{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCrds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(crdsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CrdList{})
	return err
}

// Patch applies the patch and returns the patched crd.
func (c *FakeCrds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Crd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(crdsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Crd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crd), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied crd.
func (c *FakeCrds) Apply(ctx context.Context, crd *makecrdcomv1alpha1.CrdApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Crd, err error) {
	if crd == nil {
		return nil, fmt.Errorf("crd provided to Apply must not be nil")
	}
	data, err := json.Marshal(crd)
	if err != nil {
		return nil, err
	}
	name := crd.Name
	if name == nil {
		return nil, fmt.Errorf("crd.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(crdsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.Crd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crd), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeCrds) ApplyStatus(ctx context.Context, crd *makecrdcomv1alpha1.CrdApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Crd, err error) {
	if crd == nil {
		return nil, fmt.Errorf("crd provided to Apply must not be nil")
	}
	data, err := json.Marshal(crd)
	if err != nil {
		return nil, err
	}
	name := crd.Name
	if name == nil {
		return nil, fmt.Errorf("crd.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(crdsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.Crd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Crd), err
}
