/*
Copyright Saurov.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	makecrdcomv1alpha1 "github.com/souravbiswassanto/crd/pkg/apis/makecrd.com/v1alpha1"
	versioned "github.com/souravbiswassanto/crd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/souravbiswassanto/crd/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/souravbiswassanto/crd/pkg/client/listers/makecrd.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CrdInformer provides access to a shared informer and lister for
// Crds.
type CrdInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CrdLister
}

type crdInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCrdInformer constructs a new informer for Crd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCrdInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCrdInformer constructs a new informer for Crd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MakecrdV1alpha1().Crds(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MakecrdV1alpha1().Crds(namespace).Watch(context.TODO(), options)
			},
		},
		&makecrdcomv1alpha1.Crd{},
		resyncPeriod,
		indexers,
	)
}

func (f *crdInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCrdInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *crdInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&makecrdcomv1alpha1.Crd{}, f.defaultInformer)
}

func (f *crdInformer) Lister() v1alpha1.CrdLister {
	return v1alpha1.NewCrdLister(f.Informer().GetIndexer())
}
